name: Build

on:
  workflow_call:
    inputs:
      ref:
        default: ''
        required: false
        type: string
  pull_request:
    branches:
      - '*'


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ (inputs.ref || '') }}

      - name: Build
        run: sh ./.github/workflows/build.sh

      - name: Upload Arch artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.pkg.tar.zst
          name: arch-packages

      - name: Upload Deb artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.deb
          name: deb-packages

      - name: Upload Asar artifacts
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/*.asar
          name: asar-packages

      - name: Upload Release Notes
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/release_notes.json

  nix-build:
    runs-on: ubuntu-latest
    env:
      NIXPKGS_ALLOW_UNFREE: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ (inputs.ref || '') }}

      - name: Install nix
        uses: cachix/install-nix-action@v22

      - uses: DeterminateSystems/magic-nix-cache-action@v2

      - name: Build yandex-music
        run: nix build --impure .#yandex-music
      - name: Build yandex-music without flakes binaries
        run: nix build --impure .#yandex-music-noflakes

