name: Build

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - 'main'


jobs:
  build:
    strategy:
      matrix:
        container: 
          - ubuntu:22.04
          - archlinux:latest
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.container }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: ./.github/workflows/build.sh

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: ./dist/*