name: Update, build and release

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - 'master'


jobs:
  update_packages:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:

      - name: Install dependencies
        run:  pacman -Syy --noconfirm && pacman -S --noconfirm git jq nix python python-requests

      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Git Access Fix
        run:  git config --global --add safe.directory "*"

      - name: Update package files
        run:  python utility/update_version.py
              python utility/generate_packages.py

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9.1.4
        id:   commit
        with:
          message: Update packages
          add: "."
          author_name: GitHub Actions
          author_email: loraner123@gmail.com"
        
      - name: Get Version
        id:   version
        run:  VERSION=$(jq -r '.ym.version' ./utility/version_info.json)
              release_name="Beta $VERSION"
              tag_name="v$VERSION"
              echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
              echo "release_name=$release_name" >> $GITHUB_OUTPUT
              echo "tag_name=$tag_name" >> $GITHUB_OUTPUT
      
    outputs:
      commited:        ${{ steps.commit.outputs.commited || github.event.head_commit }}
      commit_long_sha: ${{ steps.commit.outputs.commit_long_sha || github.event.head_commit.id}}
      commit_name:     ${{ github.event.head_commit.message || 'Update packages' }}
      tag_name:        ${{ steps.version.outputs.tag_name }}
      release_name:    ${{ steps.version.outputs.release_name }}
      version:         ${{ steps.version.outputs.VERSION }}


  build:
    needs: [update_packages]
    uses:  ./.github/workflows/build.yml
    if:    ${{ needs.update_packages.outputs.commited }}
    with:
      ref: ${{ needs.update_packages.outputs.commit_long_sha }}


  upload-release:
    needs:   [build, update_packages]
    if:      ${{ needs.update_packages.outputs.commited }}
    runs-on: ubuntu-latest
    steps:
      - name:  Checkout
        uses:  actions/checkout@v4
        with:
          ref: ${{ needs.update_packages.outputs.commit_long_sha }}

      - name: Publish package changes to AUR
        if: "${{ needs.update_packages.outputs.commited && github.ref_name == 'main' }}"
        uses: KSXGitHub/github-actions-deploy-aur@v2.7.0
        with:
          pkgname: "yandex-music"
          pkgbuild: "PKGBUILD"
          updpkgsums: false
          allow_empty_commits: true
          commit_username: "cucumber-sp"
          commit_email: "loraner123@gmail.com"
          ssh_private_key: "${{ secrets.AUR_SSH_PRIVATE_KEY }}"
          commit_message: "${{ needs.update_packages.outputs.commit_name }}"
          ssh_keyscan_types: "rsa,dsa,ecdsa,ed25519"

      - name:  Download artifact
        uses:  actions/download-artifact@v4
        with:
          merge-multiple: true
          path: dist

      - name: Install packages
        run:  sudo apt-get update -y
              sudo apt-get install jq -y
      
      - name: Get Release Notes HTML 
        id:   release_notes
        run:  echo "release_html=$(jq -r --arg version "${{ needs.update_packages.outputs.version }}" '.["desktop-release-notes." + $version]' ./dist/release_notes.json)" >> $GITHUB_OUTPUT

      - run:  rm -rf dist/release_notes.json

      - name: Tag Repo
        uses: richardsimko/update-tag@v1
        with:
          tag_name: ${{ needs.update_packages.outputs.tag_name}}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload files to a GitHub release
        uses: ncipollo/release-action@v1.13.0
        if:   ${{ github.ref_name == 'main' }}
        with:
          allowUpdates: true
          artifacts: dist/*
          makeLatest: true
          name: ${{ needs.update_packages.outputs.release_name }}
          replacesArtifacts: true
          tag: ${{ needs.update_packages.outputs.tag_name }}
          body: ${{ steps.release_notes.outputs.release_html }}

